/**
 * The Settlement class represents a settlement in the game. It manages the population,
 * the city tile, surrounding tiles, and the work status of each tile. It also calculates
 * the generated gold, food, and production based on the tiles worked.
 */
public class Settlement {
	
	private int population;
	private Tile cityTile;
	private Tile[][] tiles;
	private boolean[][] tilesWorked;
	
	/**
	 * 
	 * Constructs a settlement with the specified population, city tile, and surrounding tiles
	 * 
	 * 
	 * @param population is the population of the settlement 
	 * @param cityTile is the title represnting the city center
	 * @param tiles is a 2D array of tiles representing the surrounding area
	 * @param workedTiles is a boolean array indicating whihc tiles are being worked
	 */
	public Settlement(int population, Tile cityTile, Tile[][] tiles, boolean[][] workedTiles) {
		this.population = population;
		this.cityTile = cityTile;
		this.tiles = tiles;
		this.tilesWorked = workedTiles;
	}
	
	/**
	 * 
	 * Calculates and returns the total amount of gold generated by the settlment
	 * The gold is the sum of the gold generated by the city tile and the tiles being worked
	 * 
	 * 
	 * @return the total amount of generated gold
	 */
	public int getGeneratedGold() {
		int gold = cityTile.getGold().getAmount();
		for(int row = 0; row < tiles.length; row++) {
			for(int col = 0; col < tiles[row].length; col++) {
				if (tiles[row][col] != null && tilesWorked[row][col]) {
					gold += tiles[row][col].getGold().getAmount();
				}
			}
		}
		return gold;
	}
	
	/**
	 * Calculates and returns the total amount of food generated by the settlement.
     * The food is the sum of the food generated by the city tile and the tiles being worked.
	 * 
	 * @return the total amount of food generated
	 */
	public int getGeneratedFood() {
		int food = cityTile.getFood().getAmount();
		for (int row = 0; row < tiles.length; row++) {
			for (int col = 0; col < tiles[row].length; col++) {
				if (tiles[row][col] != null && tilesWorked[row][col]) {
					food += tiles[row][col].getFood().getAmount();
				}
			}
		}
		return food;
	}
	

	/**
     * Calculates and returns the total amount of production (Prod) generated by the settlement.
     * The production is the sum of the production generated by the city tile and the tiles being worked.
     * 
     * @return the total amount of generated production
     */
	public int getGeneratedProd() {
		int prod = cityTile.getProd().getAmount();
		for (int row = 0; row < tiles.length; row++) {
			for (int col = 0; col < tiles[row].length; col++) {
				if (tiles[row][col] != null && tilesWorked[row][col]) {
					prod += tiles[row][col].getProd().getAmount();
				}
			}
		}
		return prod;
	}
	
}